version: '2'
services:
  db:
    image: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec puma -b tcp://0.0.0.0:3000
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
