# The "main" Dockerfile is concerned with running on MoJ
# production infrastructure. This is a simplified Dockerfile
# for running the project locally.

FROM ruby:2.3.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ADD Gemfile /usr/src/app/Gemfile
ADD Gemfile.lock /usr/src/app/Gemfile.lock
RUN bundle install --with development test
ADD . /usr/src/app
